image: capnproto-gitlab-builder

stages:
  - build
  - quality

build:
  stage: build
  script:
    - mvn -e -X clean compile

test:
  stage: quality
  dependencies:
    - build
  script:
    - mvn -e -X test

