#!/bin/bash
BIN_PATH=`dirname "$0"`
cd $BIN_PATH

mkdir -p src/main/generated/org/capnproto/examples
capnp compile -I ../compiler/src/main/schema/  --src-prefix=src/main/schema/ -o../capnpc-java:src/main/generated/org/capnproto/examples src/main/schema/*.capnp

