#!/bin/bash
BIN_PATH=`dirname "$0"`
cd $BIN_PATH

mkdir -p compiler src/test/generated
capnp compile -I src/main/schema/  --src-prefix=src/test/schema/ -o../capnpc-java:src/test/generated src/test/schema/test.capnp src/test/schema/test-import.capnp

